### ISSUE TITLE
Is the code for "Community detection in networks with unobserved edges" to be released?

### ISSUE THREAD

**Issue by versae** [tillahoffmann/time_series#1]
After reading the [paper published on the arXiv](https://arxiv.org/abs/1808.06079), I was wondering if there is an estimate date for the publication of the accompanying code as linked in the paper.

**Comment by tillahoffmann** [comment]
Yes, we plan to release the code and associated data but haven't got around to updating the repository here. I hope to get that done over the next week.

**Comment by versae** [comment]
Awesome! Thanks.

**Comment by tillahoffmann** [comment]
@versae, I've added the majority of the code but still need to sort through some of the notebooks. They aren't particularly clean atm; let me know if you need assistance to get them to run.

* `data` contains the raw data
* `figures` contains the figures produced by running the notebooks
* `notebooks` contains Jupyter notebooks
* `time_series` is some library code for setting up the graphical models

Hope it's useful!

**Comment by versae** [comment]
That's great! I'll let you know if we run into any issue. Thank you for making this code available and congrats on the paper.
